FROM golang:buster
ARG RELEASE=master

RUN apt-get update && apt-get install -y inetutils-ping \
    wget \
    curl \
    jq \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Install Ethdo
RUN go install github.com/wealdtech/ethdo@$RELEASE
